craigslistclone/config/routes.rb
require_dependency "subdomain.rb"
Craigslistclone::Application.routes.draw do
  resources :stories

  resources :searches

  devise_for :users
  constraints(Subdomain) do
    match '/' => 'cities#show'
  end
  
  root :to => 'cities#index'
  resources :cities do
     resources :categories
   end
   
  resources :groups do
    resources :posts
  end

  resources :categories do 
    resources :posts
  end
  
  resources :posts
  
  
  

end

craigslistclone/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

craigslistclone/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    
    @category = Category.new(params[:category])
  

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

craigslistclone/app/helpers/categories_helper.rb
module CategoriesHelper
end

craigslistclone/app/views/categories/_form.html.erb
<%= form_for([@city, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

craigslistclone/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

craigslistclone/app/views/categories/index.html.erb
  <% @categories.group_by(&:group).each do |group, categories| %>
    <h3><%= link_to group, group_posts_path(group)  %></h3>
    <% categories.each do | category | %>
      <%= link_to category.title, category_posts_path(category) %> 
      <%= category.posts.count %><br>
    <% end %>
  <% end %>
  
  

<br />

<%= link_to 'New Category', new_category_path %>

craigslistclone/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

craigslistclone/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Group:</b>
  <%= @category.group %>
</p>



  <% @category.posts.each do |post| %>
  <%= link_to post.content, category_post_path(@category, post)%>
  <% end %>

<%= link_to 'New Post', new_category_post_path(@category)%> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>