craigslistclone/config/routes.rb
require_dependency "subdomain.rb"
Craigslistclone::Application.routes.draw do
  resources :stories

  resources :searches

  devise_for :users
  constraints(Subdomain) do
    match '/' => 'cities#show'
  end
  
  root :to => 'cities#index'
  resources :cities do
     resources :categories
   end
   
  resources :groups do
    resources :posts
  end

  resources :categories do 
    resources :posts
  end
  
  resources :posts
  
  
  

end

craigslistclone/app/models/search.rb
class Search < ActiveRecord::Base
  
  def posts
    @posts ||= find_posts
  end

  private

  def find_posts
    Post.find(:all, :conditions => conditions)
  end

  def keyword_conditions
    ["posts.title LIKE ?", "%#{keywords}%"] unless keywords.blank?
  end

  def minimum_price_conditions
    ["posts.price >= ?", minimum_price] unless minimum_price.blank?
  end

  def maximum_price_conditions
    ["posts.price <= ?", maximum_price] unless maximum_price.blank?
  end

  def category_conditions
    ["posts.category_id = ?", category_id] unless category_id.blank?
  end

  def conditions
    [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_clauses
    conditions_parts.map { |condition| condition.first }
  end

  def conditions_options
    conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def conditions_parts
    private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
  end
      
end

craigslistclone/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search,  }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :ok }
    end
  end
end

craigslistclone/app/helpers/searches_helper.rb
module SearchesHelper
end

craigslistclone/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Category" %><br />
    <%= f.select :category_id, [[""]] + Category.all.collect{|x| [x.title,x.id]} %>
  </div>
  <div class="field">
    <%= f.label :minimum_price %><br />
    <%= f.text_field :minimum_price %>
  </div>
  <div class="field">
    <%= f.label :maximum_price %><br />
    <%= f.text_field :maximum_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

craigslistclone/app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

craigslistclone/app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Keywords</th>
    <th>Category</th>
    <th>Minimum price</th>
    <th>Maximum price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.keywords %></td>
    <td><%= search.category_id %></td>
    <td><%= search.minimum_price %></td>
    <td><%= search.maximum_price %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

craigslistclone/app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

craigslistclone/app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<% @search.posts.each do |post| %>
  <%= post.title %>
  <%= post.content %><br />
<% end %>