craigslistclone/config/routes.rb
require_dependency "subdomain.rb"
Craigslistclone::Application.routes.draw do
  resources :stories

  resources :searches

  devise_for :users
  constraints(Subdomain) do
    match '/' => 'cities#show'
  end
  
  root :to => 'cities#index'
  resources :cities do
     resources :categories
   end
   
  resources :groups do
    resources :posts
  end

  resources :categories do 
    resources :posts
  end
  
  resources :posts
  
  
  

end

craigslistclone/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  belongs_to :city
  #validates_presence_of :user_id
  validates_presence_of :title
  validates_presence_of :content
  mount_uploader :picture, PictureUploader
  
end

craigslistclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_category
  #before_filter :authenticate_user!, only: [:create, :edit, :new]
  # GET /posts
  # GET /posts.json
  def index
    
    if @category
      @posts = @category.posts.where(:city_id => current_city.id)
    elsif params[:group_id]
      @posts = Post.where(:category_id => Category.where(:group => params[:group_id], :city_id => current_city.id).collect(&:id))
    elsif current_city
      if params[:search]
        @posts = current_city.posts.where(["title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%"])
      else
        @posts = current_city.posts
      end
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new(:category_id => @category.try(:id))
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    if @category
      @post = @category.posts.build(params[:post])
    else
      @post = Post.new(params[:post])
    end
    @post.user = current_user
    @post.city = current_city
    respond_to do |format|
      if @post.save
        format.html { redirect_to [@category, @post], notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to [@category, @post], notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to category_posts_url(@category) }
      format.json { head :ok }
    end
  end
  
  private
  
  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id]
  end
end

craigslistclone/app/helpers/posts_helper.rb
module PostsHelper
end

craigslistclone/app/views/posts/_form.html.erb
<%= form_for([@category, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Category" %><br />
    <%= f.select :category_id, Category.all.collect{|x| [x.title,x.id]} %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

craigslistclone/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', [@post.category, @post] %> |
<%= link_to 'Back', category_posts_path(@post.category) %>

craigslistclone/app/views/posts/index.html.erb
<%= content_tag :h1, @category.title if @category %>

<div id='searchresults'>
  <table>
    <tr>
      <% @posts.each do |post| %>
        <td>
          <%= link_to [post.category, post] do %>
            <%= image_tag post.picture.thumb.url  %><br />
            <div class="below-image">
              <% if post.price %>
                <span class="price">
                  $<%= post.price %>
                </span>
              <% end %>
              <%= post.title %>
            </div>
          <% end %>
        </td>
      <% end %>
    </tr>
  </table>
</div>



<%= link_to 'New Post', new_category_post_path(@category) if @category %>

craigslistclone/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', category_posts_path(@category) if @category %>

craigslistclone/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Title:</b>
  <%= @post.title %>
  <%= "$"%><%= @post.price %><br /><br />
  <%= @post.content %><br />
  <%= image_tag @post.picture unless @post.picture.blank? %>
</p>




<%= link_to 'Edit', edit_category_post_path(@post.category, @post) %> |
<%= link_to 'Back', category_posts_path(@post.category) %>