craigslistclone/config/routes.rb
require_dependency "subdomain.rb"
Craigslistclone::Application.routes.draw do
  resources :stories

  resources :searches

  devise_for :users
  constraints(Subdomain) do
    match '/' => 'cities#show'
  end
  
  root :to => 'cities#index'
  resources :cities do
     resources :categories
   end
   
  resources :groups do
    resources :posts
  end

  resources :categories do 
    resources :posts
  end
  
  resources :posts
  
  
  

end

craigslistclone/app/models/city.rb
class City < ActiveRecord::Base
  has_many :categories
  has_many :posts
  has_many :stories
  mount_uploader :picture, PictureUploader
  
end

craigslistclone/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
   # @city = City.find(params[:id])
   
    if City.find_by_subdomain(request.subdomain)
      @city = City.find_by_subdomain(request.subdomain)
    else
      @city = City.find(params[:id])
    end
    
    @posts = @city.posts.order("created_at desc").limit(5).all
    
    @stories = @city.stories
    @search = Search.new
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :ok }
    end
  end
end

craigslistclone/app/helpers/cities_helper.rb
module CitiesHelper
end

craigslistclone/app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
     <%= f.label :picture %><br />
     <%= f.file_field :picture %>
   </div>
   <div class="field">
     <%= f.label :subdomain %><br />
     <%= f.text_field :subdomain %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

craigslistclone/app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

craigslistclone/app/views/cities/index.html.erb
<div class="citylist">
<table>
   <tr>
     <% @cities.each do |city| %>
       <% next if city.picture.try(:thumb).blank? %>
       <td>
         <%= link_to root_url(:subdomain => city.subdomain) do %>
           <%= image_tag city.picture.thumb unless city.picture.try(:thumb).blank? %><br />
         <% end %>
       </td>
     <% end %>
   </tr>
 </table>
</div>

<%= link_to 'New City', new_city_path %>

craigslistclone/app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

craigslistclone/app/views/cities/show.html.erb
<div id="top">
  <%= image_tag "nacnak_banner333434.jpg", :id => 'logo' %><br>
  <%= image_tag "353.png" %>
  <%= form_tag(posts_path, :method => :get) do %>
      <div id="search">
        <%= text_field_tag 'search', '', :id => 'search' %>
        <%= submit_tag 'Search'%>
      </div>
      <div id="change_community">
        <%= link_to @city.name + " (change)", cities_path %>
      </div>
  <% end %>
  <span id="post_button">
    <%= link_to "Create a FREE Post", new_post_path %>
  </span>
</div>
<div id = "recent_posts">
  <h3>Recent Posts</h3>
  <table>
    <tr>
      <% @posts.each do |post| %>
        <% next if post.picture.try(:thumb).blank? %>
        <td>
          <%= link_to [post.category, post] do %>
            <%= image_tag post.picture.thumb unless post.picture.try(:thumb).blank? %>
            <div class="below-image">
              <% if post.price %>
                <span class="price">
                  $<%= post.price %>
                </span>
              <% end %>
              <%= post.title %>
            </div>
          <% end %>
        </td>
      <% end %>
    </tr>
  </table>
</div>
<% if false%>
<!--
<p id="notice"><%= notice %></p>

<div id="searchbar">
  <%= link_to "Search", new_search_path %> 
</div>

<div id="post">
  <%= link_to "Create a Free Post!", new_post_path %>
</div>

<p>
  <%= @city.name %>
</p>
<br />
Recent posts
<br />
<br />

<table>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, [post.category, post] %></td>
      <td>-posted by <%= post.user.email %></td>
      <td><%= image_tag post.picture %></td>
    </tr>
  <% end %>
</table>
<br /><br /><br />
Stories
<table>
  <% @stories.each do |story| %>
    <tr>
      <td><%= link_to story.title, story %></td>
      <td><%= story.author %></td>
      <td><%= image_tag story.picture unless story.picture.blank? %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', cities_path %>
-->
<% end %>